//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewsBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;rss&quot;:{&quot;@xmlns:dc&quot;:&quot;http://purl.org/dc/elements/1.1/&quot;,&quot;@xmlns:content&quot;:&quot;http://purl.org/rss/1.0/modules/content/&quot;,&quot;@xmlns:atom&quot;:&quot;http://www.w3.org/2005/Atom&quot;,&quot;@xmlns:media&quot;:&quot;http://search.yahoo.com/mrss/&quot;,&quot;@xmlns:feedburner&quot;:&quot;http://rssnamespace.org/feedburner/ext/1.0&quot;,&quot;@version&quot;:&quot;2.0&quot;,&quot;channel&quot;:{&quot;title&quot;:{&quot;#cdata-section&quot;:&quot;CNN.com - RSS Channel - Mobile App Manual&quot;},&quot;description&quot;:{&quot;#cdata-section&quot;:&quot;CNN.com delivers up-to-the-minute news and information on the latest top stories, weather, entertainment, pol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSONTest {
            get {
                return ResourceManager.GetString("JSONTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;@version&quot;: &quot;2.0&quot;,
        ///   &quot;channel&quot;: {
        ///      &quot;title&quot;: &quot;NYT &gt; World&quot;,
        ///      &quot;link&quot;: [
        ///         &quot;http://www.nytimes.com/pages/world/index.html?partner=rss&amp;emc=rss&quot;,
        ///         {
        ///            &quot;@rel&quot;: &quot;self&quot;,
        ///            &quot;@href&quot;: &quot;http://www.nytimes.com/services/xml/rss/nyt/World.xml&quot;
        ///         }
        ///      ],
        ///      &quot;description&quot;: [],
        ///      &quot;language&quot;: &quot;en-us&quot;,
        ///      &quot;copyright&quot;: &quot;Copyright 2017 The New York Times Company&quot;,
        ///      &quot;lastBuildDate&quot;: &quot;Sun, 05 Feb 2017 19:12:33 GMT&quot;,
        ///      &quot;image&quot;: {
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSONTest2 {
            get {
                return ResourceManager.GetString("JSONTest2", resourceCulture);
            }
        }
    }
}
